%get_doily_velocities
S={...
      {{'2411','',0,'Temp',2}},...
      {{'','%d %d %d %d',4,'PointNumber',3},{'-1','',0,'',6}},...
      {{'','%f %f %f',3,'Coordinates',2}},...
      {{'','%d %d %d %d',1,'FreqPointNumber',5}},...
      {{'','%f %f %f %f %f %f',-2,'Velocity',4}},...
      {{'Frequency band:','%f',1,'Frequency',4,'skip(7);'}}...
   };
D=scan_file('DoilyQuad1.txt',S);
%D=scan_file('x.txt',S);