function master_zoom_plot()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load master_zoom_plot                  

a = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'Name','Default Plot', ...
	'PointerShapeCData',mat1, ...
	...%'Position',[230 84 560 420], ...
	'Tag','Fig1');
b = uimenu('Parent',a, ...
	'Label','Visibility', ...
	'Tag','Visibility');
c = uimenu('Parent',b, ...
	'Callback','master_zoom_plot_control Show', ...
	'Label','Show Zoom Bars', ...
	'Tag','Show');
c = uimenu('Parent',b, ...
	'Callback','master_zoom_plot_control Hide', ...
	'Label','Hide Zoom Bars', ...
	'Tag','Hide');
b = uimenu('Parent',a, ...
	'Callback','master_zoom_plot_control Zoom_Points', ...
	'Label','Zoom_Points', ...
	'Tag','Zoom Points');
b = uimenu('Parent',a, ...
	'Callback','master_zoom_plot_control Clear_Points', ...
	'Label','Clear_Points', ...
	'Tag','Clear Points');
b = axes('Parent',a, ...
	'Units','points', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color',[1 1 1], ...
	'ColorOrder',mat2, ...
	'Position',[57 51 299.25 232.5], ...
	'Tag','MainAxes', ...
	'XColor',[0 0 0], ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[0.498744 -0.0728155 0], ...
	'String','time (sec)', ...
	'Tag','Text1', ...
	'VerticalAlignment','cap');
set(get(c,'Parent'),'XLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.071608 0.5 0], ...
	'Rotation',90, ...
	'Tag','Text2', ...
	'VerticalAlignment','baseline');
set(get(c,'Parent'),'YLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','right', ...
	'Position',[-0.192211 1.13754 0], ...
	'Tag','Text3', ...
	'Visible','off');
set(get(c,'Parent'),'ZLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[0.498744 1.02751 0], ...
	'Tag','Text4', ...
	'VerticalAlignment','bottom');
set(get(c,'Parent'),'Title',c);
b = axes('Parent',a, ...
	'Units','points', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color',[1 1 1], ...
	'ColorOrder',mat3, ...
	'Position',[354 51 63.75 232.5], ...
	'Tag','AuxAxes', ...
	'Visible','off', ...
	'XColor',[0 0 0], ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[0.494048 -0.0728155 0], ...
	'Tag','Text5', ...
	'VerticalAlignment','cap', ...
	'Visible','off');
set(get(c,'Parent'),'XLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.339286 0.5 0], ...
	'Rotation',90, ...
	'Tag','Text6', ...
	'VerticalAlignment','baseline', ...
	'Visible','off');
set(get(c,'Parent'),'YLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','right', ...
	'Position',[-5.625 1.13754 0], ...
	'Tag','Text7', ...
	'Visible','off');
set(get(c,'Parent'),'ZLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[0.494048 1.02751 0], ...
	'Tag','Text8', ...
	'VerticalAlignment','bottom', ...
	'Visible','off');
set(get(c,'Parent'),'Title',c);
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Position',[2.25 11.25 26.25 8.25], ...
	'String','zoom x', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Position',[2.25 0.75 26.25 9.75], ...
	'String','pan x', ...
	'Style','text', ...
	'Tag','StaticText1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Position',[3 21.75 8.25 11.25], ...
	'String','Z', ...
	'Style','text', ...
	'Tag','StaticText2');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Position',[11.25 20.25 9.75 12.75], ...
	'String','P', ...
	'Style','text', ...
	'Tag','StaticText3');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Position',[160.5 9.75 7.5 10.5], ...
	'String','+', ...
	'Style','text', ...
	'Tag','StaticText4');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[211.5 3 204 15.75], ...
	'Style','edit', ...
	'Tag','DispXY');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Position',[177.75 5.25 30.75 10.5], ...
	'String','x,y,dx,dy', ...
	'Style','text', ...
	'Tag','StaticText5');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Callback','master_zoom_plot_control slider', ...
	'Min',-1, ...
	'Position',[3 62.25 8.25 123.75], ...
	'Style','slider', ...
	'Tag','ZoomY');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Callback','master_zoom_plot_control slider', ...
	'Min',-1, ...
	'Position',[13.5 62.25 9.75 122.25], ...
	'Style','slider', ...
	'Tag','PanY');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Callback','master_zoom_plot_control slider', ...
	'Min',-1, ...
	'Position',[36.75 13.5 115.5 11.25], ...
	'Style','slider', ...
	'Tag','ZoomX');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Callback','master_zoom_plot_control slider', ...
	'Min',-1, ...
	'Position',[36 1.5 118.5 9.75], ...
	'Style','slider', ...
	'Tag','PanX');
